version: '2'

services:
  app:
    container_name: fs2netd-nodejs
    build: .
    depends_on:
      - db
    ports:
      - "8080:80"
      - "5000:5000"

  db:
    container_name: fs2netd-db
    image: mysql:5.6.26
    environment:
     - MYSQL_USER=root
     - MYSQL_ROOT_PASSWORD=root
     - MYSQL_DATABASE=fs2netd-sequelize
    volumes:
      - fs2net-db-datavolume:/var/lib/mysql
volumes:
  fs2net-db-datavolume: