db:
  dialect: 'mysql'
  host: 'localhost'
  #port: 1234 # Uncomment if non-default port should be used
  user: 'root'
  pass: ''
  database: 'fs2netd-sequelize'
  connectionLimit: 100

game_server:
  port: 5000