db:
  dialect: 'mysql'
  host: 'localhost'
  #port: 1234 # Uncomment if non-default port should be used
  user: 'root'
  pass: ''
  database: 'fs2netd-sequelize'
  connectionLimit: 100

game_server:
  port: 5000

web:
  port: 8080
  jwt: # Options for REST API JWT tokens
    secret: 'my secret' # Replace with proper secret in production
    expires_in: '7d' # Specifies when a JWT expires, accepts strings for https://github.com/rauchg/ms.js
  # tls:
    # key: file.key # Specify TLS key file here
    # cert: file.cert # Specify TLS certificate file here