db:
  dialect: 'mysql'
  host: 'db'
  user: 'root'
  pass: 'root'
  database: 'fs2netd-sequelize'
  connectionLimit: 100

game_server:
  port: 5000

web:
  port: 80
  host: 0.0.0.0
  jwt: # Options for REST API JWT tokens
    secret: 'my secret' # Replace with proper secret in production
    expires_in: '7d' # Specifies when a JWT expires, accepts strings for https://github.com/rauchg/ms.js
  # tls:
    # key: file.key # Specify TLS key file here
    # cert: file.cert # Specify TLS certificate file here